version: "3.8"

services:
  database:
    image: postgres
    container_name: tessera_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tessera_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: tessera
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
