version: "3.7"

services:
  database:
    image: postgres
    container_name: tesserat_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tesserat_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tesserat_network

  app:
    build: .
    container_name: tesserat
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - tesserat_network

volumes:
  pgdata:
    driver: local

networks:
  tesserat_network:
